# -*- coding: utf-8 -*-
"""tractor-sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpBlG-cIfoaLatB4aelK5gHNo5MrzqEs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
#

df=pd.read_csv('/content/Tractor-Sales.csv')

df

df.dtypes

df.dtypes

df['Month-Year'] = pd.to_datetime(df['Month-Year'], format='%b-%y')

df.dtypes

df

df1=df.set_index("Month-Year")

df1

plt.plot(df1)

four_month_moving_avg=df1.rolling(4).mean()

four_month_moving_avg

plt.plot(four_month_moving_avg)

six_month_moving_avg=df1.rolling(6).mean()

six_month_moving_avg

plt.plot(six_month_moving_avg)
nine_month_moving_avg=df1.rolling(9).mean()
plt.plot(nine_month_moving_avg)
twelve_month_moving_avg=df1.rolling(12).mean()
plt.plot(twelve_month_moving_avg)

import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x=four_month_moving_avg.index, y=four_month_moving_avg['Number of Tractor Sold'], mode='lines', name='4-Month Moving Average'))
fig.add_trace(go.Scatter(x=six_month_moving_avg.index, y=six_month_moving_avg['Number of Tractor Sold'], mode='lines', name='6-Month Moving Average'))
fig.add_trace(go.Scatter(x=nine_month_moving_avg.index, y=nine_month_moving_avg['Number of Tractor Sold'], mode='lines', name='9-Month Moving Average'))
fig.add_trace(go.Scatter(x=twelve_month_moving_avg.index, y=twelve_month_moving_avg['Number of Tractor Sold'], mode='lines', name='12-Month Moving Average'))

fig.update_layout(title='Tractor Sales Moving Averages', xaxis_title='Month-Year', yaxis_title='Number of Tractor Sold')
fig.show()

from statsmodels.tsa.seasonal import seasonal_decompose

seasonal_decompose(df1['Number of Tractor Sold']).plot()



decomposition = seasonal_decompose(df1['Number of Tractor Sold'])

fig = go.Figure()

fig.add_trace(go.Scatter(x=df1.index, y=df1['Number of Tractor Sold'], mode='lines', name='Original'))
fig.add_trace(go.Scatter(x=df1.index, y=decomposition.trend, mode='lines', name='Trend'))
fig.add_trace(go.Scatter(x=df1.index, y=decomposition.seasonal, mode='lines', name='Seasonal'))
fig.add_trace(go.Scatter(x=df1.index, y=decomposition.resid, mode='lines', name='Residual'))

fig.update_layout(title='Tractor Sales Seasonal Decomposition', xaxis_title='Month-Year', yaxis_title='Number of Tractor Sold')
fig.show()

fig = go.Figure()

# Plot historical data
fig.add_trace(go.Scatter(x=df1.index, y=df1['Number of Tractor Sold'], mode='lines', name='Historical Sales'))

# Plot forecasted values
fig.add_trace(go.Scatter(x=forecast.index, y=forecast, mode='lines', name='Forecasted Sales', line=dict(color='red', dash='dash')))

fig.update_layout(
    title='Tractor Sales: Historical vs. Forecasted',
    xaxis_title='Month-Year',
    yaxis_title='Number of Tractor Sold',
    hovermode='x unified'
)

fig.show()

from statsmodels.tsa.holtwinters import ExponentialSmoothing

# Define the model parameters based on observations from seasonal decomposition
# For this dataset, let's assume an additive trend and additive seasonality.
# The seasonal_periods should be 12 for monthly data.
model = ExponentialSmoothing(df1['Number of Tractor Sold'],
                             seasonal_periods=12,
                             trend='add',
                             seasonal='add',
                             initialization_method='estimated')

# Fit the model to the data
fit = model.fit()

# Make predictions for the next 12 months
forecast = fit.forecast(12)

# Print the forecasted values
print('Forecasted values for the next 12 months:')
print(forecast)



from statsmodels.tsa.arima.model import ARIMA

# Define the ARIMA model parameters (p, d, q)
# These parameters often need to be tuned. For now, we'll start with (5,1,0).
# p: number of autoregressive terms (lag observations)
# d: number of differences needed to make the time series stationary
# q: number of moving average terms (lagged forecast errors)
arima_model = ARIMA(df1['Number of Tractor Sold'], order=(5,1,0))

# Fit the model
arima_fit = arima_model.fit()

# Make predictions for the next 12 months
arima_forecast = arima_fit.forecast(steps=12)

# Print the forecasted values
print('ARIMA Forecasted values for the next 12 months:')
print(arima_forecast)

fig = go.Figure()

# Plot historical data
fig.add_trace(go.Scatter(x=df1.index, y=df1['Number of Tractor Sold'], mode='lines', name='Historical Sales'))

# Plot ARIMA forecasted values
fig.add_trace(go.Scatter(x=arima_forecast.index, y=arima_forecast, mode='lines', name='ARIMA Forecasted Sales', line=dict(color='green', dash='dot')))

fig.update_layout(
    title='Tractor Sales: Historical vs. ARIMA Forecasted',
    xaxis_title='Month-Year',
    yaxis_title='Number of Tractor Sold',
    hovermode='x unified'
)

fig.show()

import plotly.graph_objects as go

fig = go.Figure()

# Plot historical data
fig.add_trace(go.Scatter(x=df1.index, y=df1['Number of Tractor Sold'], mode='lines', name='Historical Sales'))

# Plot ARIMA forecasted values
fig.add_trace(go.Scatter(x=arima_forecast.index, y=arima_forecast, mode='lines', name='ARIMA Forecasted Sales', line=dict(color='green', dash='dot')))

fig.update_layout(
    title='Tractor Sales: Historical vs. ARIMA Forecasted',
    xaxis_title='Month-Year',
    yaxis_title='Number of Tractor Sold',
    hovermode='x unified'
)

fig.show()

from statsmodels.tsa.statespace.sarimax import SARIMAX

"""The SARIMA model requires two sets of parameters: non-seasonal (p,d,q) and seasonal (P,D,Q,S).
*   `(p,d,q)`: Represents the order of the AutoRegressive (AR), Integrated (I), and Moving Average (MA) components for the non-seasonal part.
*   `(P,D,Q,S)`: Represents the order of the seasonal AR, I, and MA components, along with the seasonal period `S` (which is 12 for monthly data).

For an initial attempt, we can try `order=(1, 1, 1)` and `seasonal_order=(1, 1, 1, 12)`.
"""

# Define the SARIMA model parameters
# These parameters often need to be tuned for optimal performance.
sarima_model = SARIMAX(df1['Number of Tractor Sold'],
                       order=(1, 1, 1),
                       seasonal_order=(1, 1, 1, 12),
                       enforce_stationarity=False,
                       enforce_invertibility=False)

# Fit the model
sarima_fit = sarima_model.fit(disp=False)

# Make predictions for the next 12 months
sarima_forecast = sarima_fit.predict(start=len(df1), end=len(df1) + 11)

# Assign proper index to the forecast
forecast_index = pd.date_range(start=df1.index[-1] + pd.DateOffset(months=1), periods=12, freq='MS')
sarima_forecast.index = forecast_index

# Print the forecasted values
print('SARIMA Forecasted values for the next 12 months:')
print(sarima_forecast)

import plotly.graph_objects as go
import pandas as pd # Ensure pandas is imported for date_range

fig = go.Figure()

# Plot historical data
fig.add_trace(go.Scatter(x=df1.index, y=df1['Number of Tractor Sold'], mode='lines', name='Historical Sales'))

# Plot SARIMA forecasted values
fig.add_trace(go.Scatter(x=sarima_forecast.index, y=sarima_forecast, mode='lines', name='SARIMA Forecasted Sales', line=dict(color='purple', dash='dash')))

fig.update_layout(
    title='Tractor Sales: Historical vs. SARIMA Forecasted',
    xaxis_title='Month-Year',
    yaxis_title='Number of Tractor Sold',
    hovermode='x unified'
)

fig.show()

import joblib

# Save the fitted SARIMA model to a .joblib file
joblib.dump(sarima_fit, 'sarima_model.joblib')
print("SARIMA model saved to 'sarima_model.joblib'")